/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.p06;

import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoClients;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoCursor;
import com.mongodb.client.MongoDatabase;
import java.awt.Color;
import java.awt.GridLayout;
import javax.swing.JPanel;
import org.bson.Document;

/**
 *
 * @author Hanif
 */
public class CRUDMongoDB extends javax.swing.JFrame {
    public static MongoClient mongoClient;
    public static MongoDatabase mongodb;
    
    /**
     * Creates new form CRUDMongoDB
     */
    public CRUDMongoDB() {
        initComponents();
        
        try {
            mongoClient = MongoClients.create("mongodb://publik:123@serverku.my.id:27017/?authSource=admin");
            mongodb = mongoClient.getDatabase("publik");
            
            UpdateData();
        } catch (Exception e) {
            System.out.println("Error : " + e.getMessage());
        }
    }
    
    public static void UpdateData() throws Exception{
        MongoCollection<Document> col = mongodb.getCollection("koleksi");
        MongoCursor<Document> cursor = col.find().iterator();

        int index = 0;

        JPanel panel = new JPanel();
        panel.setLayout(new GridLayout(0, 1, 0, 10));
        panel.setBackground(new Color(102,255,153));

        while (cursor.hasNext()) {    
            Document document = cursor.next();

            Kartu kartu = new Kartu();

            JPanel isi = new JPanel();
            isi.setLayout(new GridLayout(0, 1, 0, 0));

            for (String key : document.keySet()) {
                if (!"_id".equals(key)) {
                    Data data = new Data();
                    data.kunci.setText(key + " :");
                    data.nilai.setText(document.get(key).toString());
                    isi.add(data);
                } else {
                    kartu.id.setText(document.get(key).toString());
                }

                kartu.DaftarData.setViewportView(isi);
            }

            panel.add(kartu);

            index++;
        }

        DaftarData.setViewportView(panel);

        TotalData.setText("Total Data : " + index);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        TambahData = new javax.swing.JButton();
        TotalData = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        DaftarData = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CRUD MongoDB");

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        TambahData.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TambahData.setText("Tambah Data");
        TambahData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahDataActionPerformed(evt);
            }
        });

        TotalData.setText("Total Data :");

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        DaftarData.setBackground(new java.awt.Color(102, 255, 153));
        DaftarData.setBorder(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(TotalData)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DaftarData)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(TambahData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 291, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TambahData)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(DaftarData, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(TotalData)
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TambahDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahDataActionPerformed
        // TODO add your handling code here:
        TambahData dialog = new TambahData(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_TambahDataActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JScrollPane DaftarData;
    private javax.swing.JButton TambahData;
    private static javax.swing.JLabel TotalData;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
