/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.p06;

import com.mongodb.client.MongoCollection;
import static com.p06.CRUDMongoDB.mongodb;
import java.awt.Component;
import java.awt.GridLayout;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.bson.Document;
import org.bson.types.ObjectId;

/**
 *
 * @author Hanif
 */
public class EditData extends javax.swing.JDialog {
    private String ID;
    private HashMap<String, String> data;
    
    /**
     * Creates new form TambahData
     */
    public EditData(String id, HashMap<String, String> data, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.ID = id;
        this.data = data;
        initComponents();
        
        try {
            JPanel panel = new JPanel();
            panel.setLayout(new GridLayout(0, 1, 0, 10));
            
            int index = 1;
            
            Input panel_input = new Input();
            panel_input.id.setText(String.valueOf(1));
            panel_input.kunci.setText("_id");
            panel_input.nilai.setText(ID);
            
            panel_input.kunci.setEnabled(false);
            panel_input.nilai.setEnabled(false);
            
            panel.add(panel_input);

            for (Map.Entry<String, String> item : data.entrySet()) {
                panel_input = new Input();
                panel_input.id.setText(String.valueOf(index+1));
                panel_input.kunci.setText(item.getKey());
                panel_input.nilai.setText(item.getValue());
                panel.add(panel_input);
                index++;
            }

            DaftarInput.setViewportView(panel);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Perbaharui = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        id = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        id1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        id2 = new javax.swing.JLabel();
        DaftarInput = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tambah Data");
        setIconImage(null);
        setResizable(false);

        Perbaharui.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Perbaharui.setText("PERBAHARUI");
        Perbaharui.setToolTipText("");
        Perbaharui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerbaharuiActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBackground(new java.awt.Color(0, 255, 0));
        jPanel2.setMinimumSize(new java.awt.Dimension(22, 30));
        jPanel2.setPreferredSize(new java.awt.Dimension(22, 30));

        id.setBackground(new java.awt.Color(51, 255, 255));
        id.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        id.setText("NO");
        jPanel2.add(id);

        jPanel3.setBackground(new java.awt.Color(0, 255, 0));

        id1.setBackground(new java.awt.Color(51, 255, 255));
        id1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        id1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        id1.setText("Nama Kolom");
        jPanel3.add(id1);

        jPanel4.setBackground(new java.awt.Color(0, 255, 0));

        id2.setBackground(new java.awt.Color(51, 255, 255));
        id2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        id2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        id2.setText("Data");
        jPanel4.add(id2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        DaftarInput.setBorder(null);
        DaftarInput.setPreferredSize(new java.awt.Dimension(343, 100));
        DaftarInput.setViewportView(null);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DaftarInput, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DaftarInput, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Perbaharui, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Perbaharui)
                .addGap(18, 18, 18))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PerbaharuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerbaharuiActionPerformed
        // TODO add your handling code here:
        try {
            MongoCollection<Document> col = mongodb.getCollection("koleksi");
            Document doc = new Document();
            
            JPanel panel = (JPanel) DaftarInput.getViewport().getView();
            
            for (Component component : panel.getComponents()) {
                Input panel_input = (Input) component;
                if (!"1".equals(panel_input.id.getText())) {
                    doc.put(panel_input.kunci.getText(), panel_input.nilai.getText());
                }
            }
            
            Document filter = new Document("_id", new ObjectId(ID));
            Document DataBaru = new Document("$set", doc);
            
            col.updateOne(filter, DataBaru);
            
            CRUDMongoDB.UpdateData();
            
            JOptionPane.showMessageDialog(this, "Berhasil Memperbaharui Data");
        } catch (Exception e) {
            System.out.println("Error : " + e.getMessage());
            JOptionPane.showMessageDialog(this, "Gagal Memperbaharui Data");
        }
        
        this.dispose();
    }//GEN-LAST:event_PerbaharuiActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane DaftarInput;
    private javax.swing.JButton Perbaharui;
    public javax.swing.JLabel id;
    public javax.swing.JLabel id1;
    public javax.swing.JLabel id2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
