/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.p06;

import com.mongodb.client.MongoCollection;
import static com.p06.CRUDMongoDB.mongodb;
import java.awt.Component;
import java.awt.GridLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.bson.Document;

/**
 *
 * @author Hanif
 */
public class TambahData extends javax.swing.JDialog {

    /**
     * Creates new form TambahData
     */
    public TambahData(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Buat = new javax.swing.JButton();
        JumlahKolom = new javax.swing.JTextField();
        Simpan = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        id = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        id1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        id2 = new javax.swing.JLabel();
        DaftarInput = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tambah Data");
        setIconImage(null);
        setPreferredSize(new java.awt.Dimension(343, 370));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Jumlah Kolom");

        Buat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Buat.setText("GO");
        Buat.setToolTipText("");
        Buat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuatActionPerformed(evt);
            }
        });

        JumlahKolom.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        Simpan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Simpan.setToolTipText("");
        Simpan.setLabel("SIMPAN");
        Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBackground(new java.awt.Color(0, 255, 0));
        jPanel2.setMinimumSize(new java.awt.Dimension(22, 30));
        jPanel2.setPreferredSize(new java.awt.Dimension(22, 30));

        id.setBackground(new java.awt.Color(51, 255, 255));
        id.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        id.setText("NO");
        jPanel2.add(id);

        jPanel3.setBackground(new java.awt.Color(0, 255, 0));

        id1.setBackground(new java.awt.Color(51, 255, 255));
        id1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        id1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        id1.setText("Nama Kolom");
        jPanel3.add(id1);

        jPanel4.setBackground(new java.awt.Color(0, 255, 0));

        id2.setBackground(new java.awt.Color(51, 255, 255));
        id2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        id2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        id2.setText("Data");
        jPanel4.add(id2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        DaftarInput.setBorder(null);
        DaftarInput.setPreferredSize(new java.awt.Dimension(343, 100));
        DaftarInput.setViewportView(null);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DaftarInput, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DaftarInput, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(JumlahKolom, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Buat)
                .addContainerGap(127, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Simpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JumlahKolom)
                    .addComponent(Buat, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Simpan)
                .addGap(18, 18, 18))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuatActionPerformed
        // TODO add your handling code here:
        try {
            JPanel panel = new JPanel();
            panel.setLayout(new GridLayout(0, 1, 0, 10));

            int jumlah_kolom = Integer.parseInt(JumlahKolom.getText());

            for (int i = 0; i < jumlah_kolom; i++) {
                Input panel_input = new Input();
                panel_input.id.setText(String.valueOf(i+1));
                panel.add(panel_input);
            }

            DaftarInput.setViewportView(panel);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_BuatActionPerformed

    private void SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanActionPerformed
        // TODO add your handling code here:
        try {
            MongoCollection<Document> col = mongodb.getCollection("koleksi");
            Document doc = new Document();
            
            JPanel panel = (JPanel) DaftarInput.getViewport().getView();
            
            for (Component component : panel.getComponents()) {
                Input panel_input = (Input) component;
                doc.put(panel_input.kunci.getText(), panel_input.nilai.getText());
            }
            
            col.insertOne(doc);
            
            CRUDMongoDB.UpdateData();
            
            JOptionPane.showMessageDialog(this, "Berhasil Menyimpan Data");
        } catch (Exception e) {
            System.out.println("Error : " + e.getMessage());
            JOptionPane.showMessageDialog(this, "Gagal Menyimpan Data");
        }
        
        this.dispose();
    }//GEN-LAST:event_SimpanActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buat;
    private javax.swing.JScrollPane DaftarInput;
    private javax.swing.JTextField JumlahKolom;
    private javax.swing.JButton Simpan;
    public javax.swing.JLabel id;
    public javax.swing.JLabel id1;
    public javax.swing.JLabel id2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
